### ISSUE TITLE
在瓷器和ptp测试了 脚本没有生效

### ISSUE THREAD

**Issue by WhaleHu** [Sec-ant/Easy-Compare#1]

**Comment by WhaleHu** [comment]
没有灰色的图标，猫站也试了一下 灰色图标也没有出来

**Comment by Sec-ant** [comment]
用的是什么浏览器？Tampermonkey显示脚本加载成功了吗？有还有请问下F12打开console之后有什么警告或者错误输出吗？

**Comment by Sec-ant** [comment]
正常情况下按钮位置在这里：
![demo4](https://user-images.githubusercontent.com/10386119/76924808-7c106b00-6912-11ea-9f6d-d9947a758c98.gif)

**Comment by WhaleHu** [comment]
看到了 好东西   
就是这个图标第一次用还真的找不到

**Comment by WhaleHu** [comment]
试了一下 神器呀，一直需要这个东西
有几个小建议和问题
就是1080p的图加载占用这个屏幕，然后鼠标滑动有点不知道滑倒哪里了。因为看不到左右上角的内容，不知道是哪个图片了。
我有个小建议,就是按住一个键拉个选框 选中几个图片，然后按照数字方式切换123那种皮上的快捷键

**Comment by Sec-ant** [comment]
> 就是1080p的图加载占用这个屏幕，然后鼠标滑动有点不知道滑倒哪里了。因为看不到左右上角的内容，不知道是哪个图片了。
> 我有个小建议,就是按住一个键拉个选框 选中几个图片，然后按照数字方式切换123那种皮上的快捷键

1. 这个可以通过按键”Q“半透明化界面，显示下面原来页面中的元素；
2. 仔细看一下关于快捷键的介绍，”W“和”E“是可以向前、向后选择图片的，配合数字键可以选择向前向后第几张。

因为这个标题下的问题已经解决了，我先把这个issue关掉了，如果有其它问题或建议欢迎提新的issue。
