### ISSUE TITLE
脚本未生效

### ISSUE THREAD

**Issue by Ti800** [Sec-ant/Easy-Compare#8]
确定右上角没有灰色图标，Tampermonkey显示加载成功且chrome为最新版
![image](https://user-images.githubusercontent.com/53323379/77741659-38270f80-7050-11ea-84de-5558f9285fd9.png)
已经尝试：
- 删掉重新安装
- 关闭其他所有拓展及脚本

**Comment by Sec-ant** [comment]
请问你是只有这个站点有问题还是任何页面都无法找到图标？那个图标是需要鼠标移动到右上角的位置，触发之后才会出现（灰色），等待一段时间之后变绿的，平常情况下是隐藏的。

具体位置见：https://github.com/Sec-ant/EasyCompare/issues/1#issuecomment-600416704

**Comment by Ti800** [comment]
...找到了,原来瞎晃是不触发，需要停一小会。

**Comment by Sec-ant** [comment]
这个问题我可能后期会调整一下，感觉大家找不到位置的居多🤣🤣
